//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CUSTOMER", Namespace="http://schemas.datacontract.org/2004/07/ReportService", IsReference=true)]
    public partial class CUSTOMER : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string ADRESAField;
        
        private short CUSTOMERIDField;
        
        private string NAMEField;
        
        private ReportService.ORDER[] ORDERField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADRESA
        {
            get
            {
                return this.ADRESAField;
            }
            set
            {
                this.ADRESAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CUSTOMERID
        {
            get
            {
                return this.CUSTOMERIDField;
            }
            set
            {
                this.CUSTOMERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this.NAMEField;
            }
            set
            {
                this.NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReportService.ORDER[] ORDER
        {
            get
            {
                return this.ORDERField;
            }
            set
            {
                this.ORDERField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ORDER", Namespace="http://schemas.datacontract.org/2004/07/ReportService", IsReference=true)]
    public partial class ORDER : System.Data.Objects.DataClasses.EntityObject
    {
        
        private ReportService.CUSTOMER CUSTOMERField;
        
        private short CUSTOMERIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMEROgCVt_ShJ CUSTOMERReferenceField;
        
        private System.DateTime DATAField;
        
        private ReportService.ORDERDETAILS[] ORDERDETAILSField;
        
        private short ORDERIDField;
        
        private System.Nullable<decimal> VALOAREField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReportService.CUSTOMER CUSTOMER
        {
            get
            {
                return this.CUSTOMERField;
            }
            set
            {
                this.CUSTOMERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CUSTOMERID
        {
            get
            {
                return this.CUSTOMERIDField;
            }
            set
            {
                this.CUSTOMERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMEROgCVt_ShJ CUSTOMERReference
        {
            get
            {
                return this.CUSTOMERReferenceField;
            }
            set
            {
                this.CUSTOMERReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DATA
        {
            get
            {
                return this.DATAField;
            }
            set
            {
                this.DATAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReportService.ORDERDETAILS[] ORDERDETAILS
        {
            get
            {
                return this.ORDERDETAILSField;
            }
            set
            {
                this.ORDERDETAILSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ORDERID
        {
            get
            {
                return this.ORDERIDField;
            }
            set
            {
                this.ORDERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VALOARE
        {
            get
            {
                return this.VALOAREField;
            }
            set
            {
                this.VALOAREField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ORDERDETAILS", Namespace="http://schemas.datacontract.org/2004/07/ReportService", IsReference=true)]
    public partial class ORDERDETAILS : System.Data.Objects.DataClasses.EntityObject
    {
        
        private ReportService.ORDER ORDERField;
        
        private short ORDERIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfORDEROgCVt_ShJ ORDERReferenceField;
        
        private string PRODUSField;
        
        private short SERIALField;
        
        private decimal VALOAREField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReportService.ORDER ORDER
        {
            get
            {
                return this.ORDERField;
            }
            set
            {
                this.ORDERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ORDERID
        {
            get
            {
                return this.ORDERIDField;
            }
            set
            {
                this.ORDERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfORDEROgCVt_ShJ ORDERReference
        {
            get
            {
                return this.ORDERReferenceField;
            }
            set
            {
                this.ORDERReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUS
        {
            get
            {
                return this.PRODUSField;
            }
            set
            {
                this.PRODUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SERIAL
        {
            get
            {
                return this.SERIALField;
            }
            set
            {
                this.SERIALField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VALOARE
        {
            get
            {
                return this.VALOAREField;
            }
            set
            {
                this.VALOAREField = value;
            }
        }
    }
}
namespace System.Data.Objects.DataClasses
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDERDETAILS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.CUSTOMER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDERDETAILS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.CUSTOMER))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDERDETAILS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.CUSTOMER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDERDETAILS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.CUSTOMER))]
    public partial class EntityObject : System.Data.Objects.DataClasses.StructuralObject
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCUSTOMEROgCVt_ShJ", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfCUSTOMEROgCVt_ShJ : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfORDEROgCVt_ShJ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMERPWs4ly6w))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfORDERPWs4ly6w))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMEROgCVt_ShJ))]
    public partial class EntityReference : System.Data.Objects.DataClasses.RelatedEnd
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfORDEROgCVt_ShJ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMERPWs4ly6w))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfORDERPWs4ly6w))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMEROgCVt_ShJ))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfORDEROgCVt_ShJ", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfORDEROgCVt_ShJ : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCUSTOMERPWs4ly6w", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfCUSTOMERPWs4ly6w : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfORDERPWs4ly6w", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfORDERPWs4ly6w : System.Data.Objects.DataClasses.EntityReference
    {
    }
}
namespace CustomerOrder
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CUSTOMER", Namespace="http://schemas.datacontract.org/2004/07/CustomerOrder", IsReference=true)]
    public partial class CUSTOMER : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string ADRESAField;
        
        private short CUSTOMERIDField;
        
        private string NAMEField;
        
        private CustomerOrder.ORDER[] ORDERField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADRESA
        {
            get
            {
                return this.ADRESAField;
            }
            set
            {
                this.ADRESAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CUSTOMERID
        {
            get
            {
                return this.CUSTOMERIDField;
            }
            set
            {
                this.CUSTOMERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this.NAMEField;
            }
            set
            {
                this.NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerOrder.ORDER[] ORDER
        {
            get
            {
                return this.ORDERField;
            }
            set
            {
                this.ORDERField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ORDER", Namespace="http://schemas.datacontract.org/2004/07/CustomerOrder", IsReference=true)]
    public partial class ORDER : System.Data.Objects.DataClasses.EntityObject
    {
        
        private CustomerOrder.CUSTOMER CUSTOMERField;
        
        private short CUSTOMERIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMERPWs4ly6w CUSTOMERReferenceField;
        
        private System.DateTime DATAField;
        
        private CustomerOrder.ORDERDETAILS[] ORDERDETAILSField;
        
        private short ORDERIDField;
        
        private System.Nullable<decimal> VALOAREField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerOrder.CUSTOMER CUSTOMER
        {
            get
            {
                return this.CUSTOMERField;
            }
            set
            {
                this.CUSTOMERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CUSTOMERID
        {
            get
            {
                return this.CUSTOMERIDField;
            }
            set
            {
                this.CUSTOMERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMERPWs4ly6w CUSTOMERReference
        {
            get
            {
                return this.CUSTOMERReferenceField;
            }
            set
            {
                this.CUSTOMERReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DATA
        {
            get
            {
                return this.DATAField;
            }
            set
            {
                this.DATAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerOrder.ORDERDETAILS[] ORDERDETAILS
        {
            get
            {
                return this.ORDERDETAILSField;
            }
            set
            {
                this.ORDERDETAILSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ORDERID
        {
            get
            {
                return this.ORDERIDField;
            }
            set
            {
                this.ORDERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VALOARE
        {
            get
            {
                return this.VALOAREField;
            }
            set
            {
                this.VALOAREField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ORDERDETAILS", Namespace="http://schemas.datacontract.org/2004/07/CustomerOrder", IsReference=true)]
    public partial class ORDERDETAILS : System.Data.Objects.DataClasses.EntityObject
    {
        
        private CustomerOrder.ORDER ORDERField;
        
        private short ORDERIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfORDERPWs4ly6w ORDERReferenceField;
        
        private string PRODUSField;
        
        private short SERIALField;
        
        private decimal VALOAREField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerOrder.ORDER ORDER
        {
            get
            {
                return this.ORDERField;
            }
            set
            {
                this.ORDERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ORDERID
        {
            get
            {
                return this.ORDERIDField;
            }
            set
            {
                this.ORDERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfORDERPWs4ly6w ORDERReference
        {
            get
            {
                return this.ORDERReferenceField;
            }
            set
            {
                this.ORDERReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUS
        {
            get
            {
                return this.PRODUSField;
            }
            set
            {
                this.PRODUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SERIAL
        {
            get
            {
                return this.SERIALField;
            }
            set
            {
                this.SERIALField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VALOARE
        {
            get
            {
                return this.VALOAREField;
            }
            set
            {
                this.VALOAREField = value;
            }
        }
    }
}
namespace System.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityContainerNameField;
        
        private System.Data.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName
        {
            get
            {
                return this.EntityContainerNameField;
            }
            set
            {
                this.EntityContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKeyMember[] EntityKeyValues
        {
            get
            {
                return this.EntityKeyValuesField;
            }
            set
            {
                this.EntityKeyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName
        {
            get
            {
                return this.EntitySetNameField;
            }
            set
            {
                this.EntitySetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMEROgCVt_ShJ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfORDEROgCVt_ShJ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.CUSTOMER[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.CUSTOMER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDER[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDERDETAILS[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportService.ORDERDETAILS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.CUSTOMER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDER[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDERDETAILS[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerOrder.ORDERDETAILS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfCUSTOMERPWs4ly6w))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfORDERPWs4ly6w))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private object ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IReport")]
public interface IReport
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IReport/GetAllCustomer", ReplyAction="http://Microsoft.ServiceModel.Samples/IReport/GetAllCustomerResponse")]
    ReportService.CUSTOMER[] GetAllCustomer();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IReport/GetAllOrdersForCustomer", ReplyAction="http://Microsoft.ServiceModel.Samples/IReport/GetAllOrdersForCustomerResponse")]
    ReportService.ORDER[] GetAllOrdersForCustomer(int _COSTUMERId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IReportChannel : IReport, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ReportClient : System.ServiceModel.ClientBase<IReport>, IReport
{
    
    public ReportClient()
    {
    }
    
    public ReportClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ReportClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ReportService.CUSTOMER[] GetAllCustomer()
    {
        return base.Channel.GetAllCustomer();
    }
    
    public ReportService.ORDER[] GetAllOrdersForCustomer(int _COSTUMERId)
    {
        return base.Channel.GetAllOrdersForCustomer(_COSTUMERId);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ICustomer")]
public interface ICustomer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICustomer/GetCustomerById", ReplyAction="http://Microsoft.ServiceModel.Samples/ICustomer/GetCustomerByIdResponse")]
    CustomerOrder.CUSTOMER GetCustomerById(int _id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICustomer/InsertCustomer", ReplyAction="http://Microsoft.ServiceModel.Samples/ICustomer/InsertCustomerResponse")]
    void InsertCustomer(string _name, string _address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICustomer/UpdateCustomer", ReplyAction="http://Microsoft.ServiceModel.Samples/ICustomer/UpdateCustomerResponse")]
    void UpdateCustomer(CustomerOrder.CUSTOMER customer);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICustomer/DeleteCustomer", ReplyAction="http://Microsoft.ServiceModel.Samples/ICustomer/DeleteCustomerResponse")]
    void DeleteCustomer(CustomerOrder.CUSTOMER customer);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICustomer/GetAllOrders", ReplyAction="http://Microsoft.ServiceModel.Samples/ICustomer/GetAllOrdersResponse")]
    ReportService.ORDER[] GetAllOrders(int _customerId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICustomerChannel : ICustomer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomerClient : System.ServiceModel.ClientBase<ICustomer>, ICustomer
{
    
    public CustomerClient()
    {
    }
    
    public CustomerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CustomerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CustomerOrder.CUSTOMER GetCustomerById(int _id)
    {
        return base.Channel.GetCustomerById(_id);
    }
    
    public void InsertCustomer(string _name, string _address)
    {
        base.Channel.InsertCustomer(_name, _address);
    }
    
    public void UpdateCustomer(CustomerOrder.CUSTOMER customer)
    {
        base.Channel.UpdateCustomer(customer);
    }
    
    public void DeleteCustomer(CustomerOrder.CUSTOMER customer)
    {
        base.Channel.DeleteCustomer(customer);
    }
    
    public ReportService.ORDER[] GetAllOrders(int _customerId)
    {
        return base.Channel.GetAllOrders(_customerId);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IOrder")]
public interface IOrder
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IOrder/GetOrder", ReplyAction="http://Microsoft.ServiceModel.Samples/IOrder/GetOrderResponse")]
    CustomerOrder.ORDER GetOrder(int _orderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IOrder/InsertOrder", ReplyAction="http://Microsoft.ServiceModel.Samples/IOrder/InsertOrderResponse")]
    void InsertOrder(int _customerId, System.DateTime dt, decimal _value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IOrder/UpdateOrder", ReplyAction="http://Microsoft.ServiceModel.Samples/IOrder/UpdateOrderResponse")]
    void UpdateOrder(CustomerOrder.ORDER order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IOrder/DeleteOrder", ReplyAction="http://Microsoft.ServiceModel.Samples/IOrder/DeleteOrderResponse")]
    void DeleteOrder(CustomerOrder.ORDER order);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IOrderChannel : IOrder, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OrderClient : System.ServiceModel.ClientBase<IOrder>, IOrder
{
    
    public OrderClient()
    {
    }
    
    public OrderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public OrderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CustomerOrder.ORDER GetOrder(int _orderId)
    {
        return base.Channel.GetOrder(_orderId);
    }
    
    public void InsertOrder(int _customerId, System.DateTime dt, decimal _value)
    {
        base.Channel.InsertOrder(_customerId, dt, _value);
    }
    
    public void UpdateOrder(CustomerOrder.ORDER order)
    {
        base.Channel.UpdateOrder(order);
    }
    
    public void DeleteOrder(CustomerOrder.ORDER order)
    {
        base.Channel.DeleteOrder(order);
    }
}
