//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TestModel", "FK_ORDER_COSTUMER", "COSTUMER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Microsoft.ServiceModel.Samples.COSTUMER), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.ServiceModel.Samples.ORDER), true)]
[assembly: EdmRelationshipAttribute("TestModel", "FK_ORDERDETAILS_ORDER", "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Microsoft.ServiceModel.Samples.ORDER), "ORDERDETAILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.ServiceModel.Samples.ORDERDETAILS), true)]

#endregion

namespace Microsoft.ServiceModel.Samples
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestEntities object using the connection string found in the 'TestEntities' section of the application configuration file.
        /// </summary>
        public TestEntities() : base("name=TestEntities", "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEntities object.
        /// </summary>
        public TestEntities(string connectionString) : base(connectionString, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEntities object.
        /// </summary>
        public TestEntities(EntityConnection connection) : base(connection, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COSTUMER> COSTUMER
        {
            get
            {
                if ((_COSTUMER == null))
                {
                    _COSTUMER = base.CreateObjectSet<COSTUMER>("COSTUMER");
                }
                return _COSTUMER;
            }
        }
        private ObjectSet<COSTUMER> _COSTUMER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ORDER> ORDER
        {
            get
            {
                if ((_ORDER == null))
                {
                    _ORDER = base.CreateObjectSet<ORDER>("ORDER");
                }
                return _ORDER;
            }
        }
        private ObjectSet<ORDER> _ORDER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ORDERDETAILS> ORDERDETAILS
        {
            get
            {
                if ((_ORDERDETAILS == null))
                {
                    _ORDERDETAILS = base.CreateObjectSet<ORDERDETAILS>("ORDERDETAILS");
                }
                return _ORDERDETAILS;
            }
        }
        private ObjectSet<ORDERDETAILS> _ORDERDETAILS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COSTUMER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOSTUMER(COSTUMER cOSTUMER)
        {
            base.AddObject("COSTUMER", cOSTUMER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ORDER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToORDER(ORDER oRDER)
        {
            base.AddObject("ORDER", oRDER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ORDERDETAILS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToORDERDETAILS(ORDERDETAILS oRDERDETAILS)
        {
            base.AddObject("ORDERDETAILS", oRDERDETAILS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="COSTUMER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COSTUMER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COSTUMER object.
        /// </summary>
        /// <param name="cUSTOMERID">Initial value of the CUSTOMERID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static COSTUMER CreateCOSTUMER(global::System.Int16 cUSTOMERID, global::System.String nAME)
        {
            COSTUMER cOSTUMER = new COSTUMER();
            cOSTUMER.CUSTOMERID = cUSTOMERID;
            cOSTUMER.NAME = nAME;
            return cOSTUMER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CUSTOMERID
        {
            get
            {
                return _CUSTOMERID;
            }
            set
            {
                if (_CUSTOMERID != value)
                {
                    OnCUSTOMERIDChanging(value);
                    ReportPropertyChanging("CUSTOMERID");
                    _CUSTOMERID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CUSTOMERID");
                    OnCUSTOMERIDChanged();
                }
            }
        }
        private global::System.Int16 _CUSTOMERID;
        partial void OnCUSTOMERIDChanging(global::System.Int16 value);
        partial void OnCUSTOMERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADRESA
        {
            get
            {
                return _ADRESA;
            }
            set
            {
                OnADRESAChanging(value);
                ReportPropertyChanging("ADRESA");
                _ADRESA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADRESA");
                OnADRESAChanged();
            }
        }
        private global::System.String _ADRESA;
        partial void OnADRESAChanging(global::System.String value);
        partial void OnADRESAChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "FK_ORDER_COSTUMER", "ORDER")]
        public EntityCollection<ORDER> ORDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDER>("TestModel.FK_ORDER_COSTUMER", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDER>("TestModel.FK_ORDER_COSTUMER", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="ORDER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ORDER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ORDER object.
        /// </summary>
        /// <param name="oRDERID">Initial value of the ORDERID property.</param>
        /// <param name="dATA">Initial value of the DATA property.</param>
        /// <param name="cUSTOMERID">Initial value of the CUSTOMERID property.</param>
        public static ORDER CreateORDER(global::System.Int16 oRDERID, global::System.DateTime dATA, global::System.Int16 cUSTOMERID)
        {
            ORDER oRDER = new ORDER();
            oRDER.ORDERID = oRDERID;
            oRDER.DATA = dATA;
            oRDER.CUSTOMERID = cUSTOMERID;
            return oRDER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ORDERID
        {
            get
            {
                return _ORDERID;
            }
            set
            {
                if (_ORDERID != value)
                {
                    OnORDERIDChanging(value);
                    ReportPropertyChanging("ORDERID");
                    _ORDERID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ORDERID");
                    OnORDERIDChanged();
                }
            }
        }
        private global::System.Int16 _ORDERID;
        partial void OnORDERIDChanging(global::System.Int16 value);
        partial void OnORDERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATA
        {
            get
            {
                return _DATA;
            }
            set
            {
                OnDATAChanging(value);
                ReportPropertyChanging("DATA");
                _DATA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA");
                OnDATAChanged();
            }
        }
        private global::System.DateTime _DATA;
        partial void OnDATAChanging(global::System.DateTime value);
        partial void OnDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CUSTOMERID
        {
            get
            {
                return _CUSTOMERID;
            }
            set
            {
                OnCUSTOMERIDChanging(value);
                ReportPropertyChanging("CUSTOMERID");
                _CUSTOMERID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUSTOMERID");
                OnCUSTOMERIDChanged();
            }
        }
        private global::System.Int16 _CUSTOMERID;
        partial void OnCUSTOMERIDChanging(global::System.Int16 value);
        partial void OnCUSTOMERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> VALOARE
        {
            get
            {
                return _VALOARE;
            }
            set
            {
                OnVALOAREChanging(value);
                ReportPropertyChanging("VALOARE");
                _VALOARE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOARE");
                OnVALOAREChanged();
            }
        }
        private Nullable<global::System.Decimal> _VALOARE;
        partial void OnVALOAREChanging(Nullable<global::System.Decimal> value);
        partial void OnVALOAREChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "FK_ORDER_COSTUMER", "COSTUMER")]
        public COSTUMER COSTUMER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COSTUMER>("TestModel.FK_ORDER_COSTUMER", "COSTUMER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COSTUMER>("TestModel.FK_ORDER_COSTUMER", "COSTUMER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<COSTUMER> COSTUMERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COSTUMER>("TestModel.FK_ORDER_COSTUMER", "COSTUMER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<COSTUMER>("TestModel.FK_ORDER_COSTUMER", "COSTUMER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "FK_ORDERDETAILS_ORDER", "ORDERDETAILS")]
        public EntityCollection<ORDERDETAILS> ORDERDETAILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDERDETAILS>("TestModel.FK_ORDERDETAILS_ORDER", "ORDERDETAILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDERDETAILS>("TestModel.FK_ORDERDETAILS_ORDER", "ORDERDETAILS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="ORDERDETAILS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ORDERDETAILS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ORDERDETAILS object.
        /// </summary>
        /// <param name="oRDERID">Initial value of the ORDERID property.</param>
        /// <param name="pRODUS">Initial value of the PRODUS property.</param>
        /// <param name="vALOARE">Initial value of the VALOARE property.</param>
        /// <param name="sERIAL">Initial value of the SERIAL property.</param>
        public static ORDERDETAILS CreateORDERDETAILS(global::System.Int16 oRDERID, global::System.String pRODUS, global::System.Decimal vALOARE, global::System.Int16 sERIAL)
        {
            ORDERDETAILS oRDERDETAILS = new ORDERDETAILS();
            oRDERDETAILS.ORDERID = oRDERID;
            oRDERDETAILS.PRODUS = pRODUS;
            oRDERDETAILS.VALOARE = vALOARE;
            oRDERDETAILS.SERIAL = sERIAL;
            return oRDERDETAILS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ORDERID
        {
            get
            {
                return _ORDERID;
            }
            set
            {
                if (_ORDERID != value)
                {
                    OnORDERIDChanging(value);
                    ReportPropertyChanging("ORDERID");
                    _ORDERID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ORDERID");
                    OnORDERIDChanged();
                }
            }
        }
        private global::System.Int16 _ORDERID;
        partial void OnORDERIDChanging(global::System.Int16 value);
        partial void OnORDERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PRODUS
        {
            get
            {
                return _PRODUS;
            }
            set
            {
                OnPRODUSChanging(value);
                ReportPropertyChanging("PRODUS");
                _PRODUS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PRODUS");
                OnPRODUSChanged();
            }
        }
        private global::System.String _PRODUS;
        partial void OnPRODUSChanging(global::System.String value);
        partial void OnPRODUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOARE
        {
            get
            {
                return _VALOARE;
            }
            set
            {
                OnVALOAREChanging(value);
                ReportPropertyChanging("VALOARE");
                _VALOARE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOARE");
                OnVALOAREChanged();
            }
        }
        private global::System.Decimal _VALOARE;
        partial void OnVALOAREChanging(global::System.Decimal value);
        partial void OnVALOAREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SERIAL
        {
            get
            {
                return _SERIAL;
            }
            set
            {
                if (_SERIAL != value)
                {
                    OnSERIALChanging(value);
                    ReportPropertyChanging("SERIAL");
                    _SERIAL = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SERIAL");
                    OnSERIALChanged();
                }
            }
        }
        private global::System.Int16 _SERIAL;
        partial void OnSERIALChanging(global::System.Int16 value);
        partial void OnSERIALChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "FK_ORDERDETAILS_ORDER", "ORDER")]
        public ORDER ORDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("TestModel.FK_ORDERDETAILS_ORDER", "ORDER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("TestModel.FK_ORDERDETAILS_ORDER", "ORDER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ORDER> ORDERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("TestModel.FK_ORDERDETAILS_ORDER", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ORDER>("TestModel.FK_ORDERDETAILS_ORDER", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
